# Generated by Django 5.2.4 on 2025-08-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='book_id',
            new_name='book',
        ),
    ]
